import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import Link from 'next/link'
import Kloa1Icon from '/public/Logo/kloa1.webp'
import Kloa2Icon from '/public/Logo/kloa2.webp'
import NavSearchForm from './NavSearchForm'
import SearchIcon from '/public/Icon/search.svg'
import SunModeIcon from '/public/Icon/sun.svg'
import MoonModeIcon from '/public/Icon/moon.svg'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'KLOA Clone Project',
  description: 'Generated by phh, KLOA Clone Project',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body>
        <div className='nav-bar'>
          <div className='nav-left'>
            <Link href='/'>
              <Image src={Kloa1Icon} alt='KLOA ICON' width={100} height={30} />
            </Link>
          </div>
          <div className='nav-center'>
            <div className='nav-list'>
              <Link href='/notices'>공지사항</Link>
              <Link href='/characters'>전투정보실</Link>
              <Link href='/merchant'>떠돌이 상인</Link>
              <Link href='/sell'>아이템 거래</Link>
              <Link href='/crow'>계산기</Link>
            </div>
            <div className='nav-search'>
              <Image src={SearchIcon} alt='SearchIcon' />
              <NavSearchForm />
            </div>
          </div>
          <div className='nav-right'>
            <button type='button'>
              <Image src={MoonModeIcon} alt='MoonMode' />
            </button>
            <Link href='/'>로그인</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  )
}
