import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header/Header'
import AuthSession from './AuthSession'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'KLOA Clone Project',
  description: 'Generated by phh, KLOA Clone Project',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className='bg-[#f5f6f7] dark:bg-[#2b2d31] h-full'>
        <AuthSession>
          <Header />
          {children}
        </AuthSession>
      </body>
    </html>
  )
}
