import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import Providers from './Provider'
import AuthSession from './AuthSession'
import Header from '@/components/Header/Header'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'KLOA Clone Project',
  description: 'Generated by phh, KLOA Clone Project',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <body className='bg-[#f5f6f7] dark:bg-[#2b2d31] h-fit'>
        <Providers>
          <AuthSession>
            <Header />
            {children}
          </AuthSession>
        </Providers>
      </body>
    </html>
  )
}
